import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{formatTelegramIssue,taipeiDate,validAnalysis} from '../worker.mjs';

function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001.sql',import.meta.url),'utf8'));const prepare=sql=>{const statement={bind(...args){return {async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return db.prepare(sql).run(...args);}};},async all(){return {results:db.prepare(sql).all()};},async run(){return db.prepare(sql).run();}};return statement;};const env={APP_KEY:'private-test-key',JOB_TOKEN:'jobs-test-key',DB:{prepare,async batch(list){db.exec('BEGIN');try{for(const q of list)await q.run();db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}},ASSETS:{fetch:()=>new Response('static')}};const call=(path,{data,cookie,job=false,origin}={})=>worker.fetch(new Request('https://example.test'+path,{method:data?'POST':'GET',headers:{...(data?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{}),...(job?{authorization:'Bearer jobs-test-key'}:{}),...(origin?{origin}:{})},body:data?JSON.stringify(data):undefined}),env);return {db,env,call};}
const issue=()=>({date:'2026-09-21',kind:'daily',headline:'Research',status:'source_only',sources:[],signals:[{id:'HN:1',title:'Example',topic:'工作流程',url:'https://example.com',excerpt:'A real excerpt'}]});
async function login(call){const res=await call('/api/login',{data:{key:'private-test-key'}});assert.equal(res.status,200);assert.match(res.headers.get('set-cookie'),/HttpOnly.*SameSite=Strict.*Secure/);return res.headers.get('set-cookie').split(';')[0];}
test('private data requires session; job token does not grant browser session',async()=>{const {call}=setup();assert.equal((await call('/api/state')).status,401);assert.equal((await call('/api/state',{job:true})).status,401);assert.equal((await call('/internal/context')).status,401);});
test('login rate limit, wrong key, and cross-origin writes',async()=>{const {call}=setup();assert.equal((await call('/api/login',{data:{key:'bad'},origin:'https://attacker.test'})).status,403);for(let i=0;i<10;i++)assert.equal((await call('/api/login',{data:{key:'bad'}})).status,401);assert.equal((await call('/api/login',{data:{key:'private-test-key'}})).status,429);});
test('feedback persists across sessions and logout revokes the session',async()=>{const {call}=setup();await call('/internal/issues',{data:issue(),job:true});const first=await login(call),second=await login(call);assert.equal((await call('/api/feedback',{cookie:first,data:{id:'HN:1',reaction:'research',saved:true,note:'Interview hypothesis'}})).status,200);const state=await (await call('/api/state',{cookie:second})).json();assert.equal(state.feedback[0].note,'Interview hypothesis');assert.equal(state.feedback[0].saved,1);await call('/api/logout',{cookie:first,data:{}});assert.equal((await call('/api/state',{cookie:first})).status,401);assert.equal((await call('/api/state',{cookie:second})).status,200);});
test('issue retries do not create duplicate issues and invalid links are rejected',async()=>{const {call}=setup();for(let i=0;i<2;i++)assert.equal((await call('/internal/issues',{job:true,data:issue()})).status,200);const context=await (await call('/internal/context',{job:true})).json();assert.equal(context.issues.length,1);const bad=issue();bad.signals[0].url='javascript:alert(1)';assert.equal((await call('/internal/issues',{job:true,data:bad})).status,400);});
test('AI citations cannot reference nonexistent sources',()=>{const card={id:'HN:1',evidence_ids:['invented']};for(const k of ['title_zh','problem','audience','alternative','inference','unknown','action','why','monetization','counterevidence'])card[k]='有內容';assert.equal(validAnalysis({cards:[card]},issue().signals),false);card.evidence_ids=['HN:1'];assert.equal(validAnalysis({cards:[card]},issue().signals),true);});
test('Telegram output keeps sections readable and model titles on one line',()=>{const item=issue();item.headline='今天，從三個\n線索開始。';item.status='analyzed';item.signals.push({id:'DEV:2',title:'Second',topic:'開發工具',url:'https://example.org',excerpt:'Excerpt',analysis:{title_zh:'第二個\n題目'}});const message=formatTelegramIssue(item,'https://founder.example');assert.equal(message,'拾題 / 2026-09-21\n今日探索 · 15 分鐘\n\n今天，從三個 線索開始。\n\n1. Example\nhttps://example.com\n\n2. 第二個 題目\nhttps://example.org\n\n分析包含待驗證假設，請對照來源。\n\n打開研究筆記：https://founder.example');});
test('AI missing binding is explicit and Telegram without secrets does not claim delivery',async()=>{const {call,db}=setup();assert.equal((await call('/internal/analyze',{job:true,data:{signals:issue().signals}})).status,503);await call('/internal/issues',{job:true,data:issue()});assert.equal((await call('/internal/deliver',{job:true,data:{date:'2026-09-21'}})).status,503);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM deliveries').get().n,0);});
test('successful Telegram delivery is sent once, ambiguous network failure is not resent',async()=>{const {call,env}=setup();env.TELEGRAM_BOT_TOKEN='fake';env.TELEGRAM_CHAT_ID='123';await call('/internal/issues',{job:true,data:issue()});let sends=0;const original=globalThis.fetch;globalThis.fetch=async()=>{sends++;return Response.json({ok:true});};try{await call('/internal/deliver',{job:true,data:{date:'2026-09-21'}});await call('/internal/deliver',{job:true,data:{date:'2026-09-21'}});assert.equal(sends,1);const second=issue();second.date='2026-09-22';await call('/internal/issues',{job:true,data:second});globalThis.fetch=async()=>{sends++;throw new Error('timeout');};assert.equal((await call('/internal/deliver',{job:true,data:{date:second.date}})).status,502);await call('/internal/deliver',{job:true,data:{date:second.date}});assert.equal(sends,2);}finally{globalThis.fetch=original;}});
test('Taipei date changes at UTC 16:00',()=>{assert.equal(taipeiDate(new Date('2026-09-20T15:59:59Z')),'2026-09-20');assert.equal(taipeiDate(new Date('2026-09-20T16:00:00Z')),'2026-09-21');});
test('model responses are parsed and per-day AI calls are bounded',async()=>{const {call,env}=setup();const card={id:'HN:1',evidence_ids:['HN:1']};for(const k of ['title_zh','problem','audience','alternative','inference','unknown','action','why','monetization','counterevidence'])card[k]='需要驗證';env.AI={async run(){return {choices:[{message:{content:JSON.stringify({cards:[card]})}}]};}};for(let i=0;i<6;i++)assert.equal((await call('/internal/analyze',{job:true,data:{signals:issue().signals}})).status,200);assert.equal((await call('/internal/analyze',{job:true,data:{signals:issue().signals}})).status,429);});
test('Telegram rate limit releases delivery claim for later recovery',async()=>{const {call,env,db}=setup();env.TELEGRAM_BOT_TOKEN='fake';env.TELEGRAM_CHAT_ID='123';await call('/internal/issues',{job:true,data:issue()});const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({ok:false,parameters:{retry_after:90}},{status:429});try{const result=await call('/internal/deliver',{job:true,data:{date:'2026-09-21'}});assert.equal(result.status,429);assert.equal((await result.json()).retry_after,90);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM deliveries').get().n,0);}finally{globalThis.fetch=original;}});
