CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS login_attempts (ip TEXT PRIMARY KEY, count INTEGER NOT NULL, reset INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS issues (date TEXT PRIMARY KEY, kind TEXT NOT NULL, body TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS signals (id TEXT PRIMARY KEY, body TEXT NOT NULL, topic TEXT NOT NULL, last_seen TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS feedback (signal_id TEXT PRIMARY KEY REFERENCES signals(id), reaction TEXT NOT NULL DEFAULT '', saved INTEGER NOT NULL DEFAULT 0, note TEXT NOT NULL DEFAULT '', updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS deliveries (date TEXT PRIMARY KEY, status TEXT NOT NULL, updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ai_budget (day TEXT PRIMARY KEY, calls INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS feedback_saved ON feedback(saved);
CREATE INDEX IF NOT EXISTS signals_seen ON signals(last_seen);
